services:
  database-agent-lease:
    image: mysql:8.0.32
    environment:
      MYSQL_DATABASE: agent_lease_test_test
      MYSQL_USER: agent_lease_test
      MYSQL_PASSWORD: agent_lease_test
      MYSQL_ROOT_PASSWORD: agent_lease_root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uagent_lease_test", "-pagent_lease_test"]
      timeout: 5s
      retries: 20
      interval: 2s
    ports:
      - "3307:3306"
    tmpfs:
      - /var/lib/mysql