# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

controllers:
    resource: routing.controllers

admin:
    resource: routes/api/admin.yaml

auth:
    resource: routes/api/auth.yaml

billing:
    resource: routes/api/billing.yaml

expense:
    resource: routes/api/expense.yaml

person:
    resource: routes/api/person.yaml
