# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

controllers:
    resource: routing.controllers

person_api:
    resource: '../src/Person/Infrastructure/Http/PersonController.php'
    type: attribute

expense_api:
    resource: '../src/Expense/Infrastructure/Http/ExpenseController.php'
    type: attribute
